version: "3.0"

services:
  beacon_node:
    image: sigp/lighthouse:latest
    volumes:
      - ./lighthouse-data:/root/.lighthouse
      - ./scripts:/root/scripts
      - ./jwttoken:/root/jwttoken
    ports:
      - 5052:5052/tcp
      - 5053:5053/tcp
      - 5054:5054/tcp     # metrics endpoint
      - 9000:9000/tcp
      - 9000:9000/udp
    env_file: .env
    command: sh /root/scripts/start-beacon-node.sh
    restart: on-failure
    stop_grace_period: 3m

  geth:
    image: ethereum/client-go:latest
    entrypoint: /bin/sh
    volumes:
      - ./geth-data:/root/.ethereum
      - ${GETH_ANCIENT_CHAINDATA_DIR}:/root/ancient-data
      - ./scripts:/root/scripts
      - ./jwttoken:/root/jwttoken
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:8546:8546"
    expose:
      - 8551
    env_file: .env
    command: /root/scripts/start-geth.sh
    restart: on-failure
    stop_grace_period: 3m
